blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'

urlpatterns = [
    path('login_page/', views.login_page, name='login_page'),
    path('logout_page/', views.logout_page, name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),

    path('', views.index, name="index"),
    path('blog/', views.PostListView.as_view(), name='blog'),
    path('post/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name="post_detail"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('search/', views.search, name="search"),
    # path('category/<int:pk>', views.category, name="category"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace="blogapp")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, related_name='categories')
    small = models.CharField(max_length=100, null=True)
    body = models.TextField()
    image = models.ImageField(upload_to="static/assets/images/", null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse('blogapp:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, related_name='comments')
    name = models.CharField(max_length=80, null=True)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


class SendMessage(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'{self.name} sent a message'

blogapp/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment, SendMessage, Category
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.core.mail import send_mail
#Register
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

# Register
# Admin: adminerali
def login_required_decorator(func):
    return login_required(func, login_url='blogapp:login_page')

@login_required_decorator
def logout_page(request):
    logout(request)
    return redirect('blogapp:login_page')

def login_page(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, password=password, username=username)
        if user is not None:
            login(request, user)
            return redirect('blogapp:index')
    return render(request, 'login.html')

class SignUpView(CreateView):
    form_class =UserCreationForm
    success_url = reverse_lazy("blogapp:login_page")
    template_name = "signup.html"

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog.html'


@login_required_decorator
def index(request):
    queryset = Post.published.all()
    queryset1 = Post.published.all()[:2]
    queryset2 = Post.published.all()[:5]
    cats = Category.objects.all()

    context = {
        "posts": queryset,
        "posts1": queryset1,
        "posts2": queryset2,
        'categories': cats,
    }
    return render(request, "index.html", context)

@login_required_decorator
def about(request):
    return render(request, "about.html")

# def contact(request):
#     return render(request, "contact.html")

# def post_detail(request):
#     return render(request, "post-details.html")

@login_required_decorator
def post_detail(request, year, month, day, slug):
    queryset = Post.published.all()
    queryset1 = Post.published.all()
    post = get_object_or_404(Post, slug=slug,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    if request.POST:
        comment = Comment()
        comment.name = request.POST.get('name', '')
        comment.email = request.POST.get('email', '')
        comment.subject = request.POST.get('subject', '')
        comment.body = request.POST.get('message', '')
        comment.post = post
        comment.save()

    return render(request, 'post-details.html',
                  {'posts': post,
                   'comments': comments,
                   "last_posts": queryset,
                   "categories": queryset1,
                   })

@login_required_decorator
def contact(request):
    if request.POST:
        model = SendMessage()
        model.name = request.POST.get('name', '')
        model.email = request.POST.get('email', '')
        model.subject = request.POST.get('subject', '')
        model.message = request.POST.get('message', '')
        model.save()
    return render(request, 'contact.html')

@login_required_decorator
def search(request):
    query = request.GET['q']

    if not query or query.isspace():
        messages.error(request, 'Please refine your search query...')
        return redirect("blogapp:blog")

    search_results = Post.objects.filter(Q(title__icontains=query) | Q(small__icontains=query) | Q(body__icontains=query))

    context = {
        'search_results': search_results,
        'query': query
    }
    return render(request, 'search.html', context)


# def category(request):
#     queryset = Category.objects.all()
#     print(queryset)
#     return render(request, 'blog.html', {'categories': queryset})

templates/about.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}About Us{% endblock %}</title>

{% block content %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>about us</h4>
                            <h2>more about us!</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->


    <section class="about-us">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <img src="{% static 'assets/images/about-us.jpg' %}" alt="">
                    <p>Assalomu alaykum avvalambor o'zim haqimda gapiradigan bo'lsam, ismi familiyam Erali Abdinazarov
                        Qashqadaryo viloyati Chiroqchi tumanida yashayman. Hozirda Sirdaryo Guliston Davlat
                        Universiteti 4-kurs talabasiman. Va Python Backend dasturchisiman, Portfolio bilan tanishing 👉
                        <a rel="nofollow"
                           href="https://t.me/eraliabdinazarov"
                           target="_parent">portfolio</a>,
                        Yana Telegram botlar ham qilib beraman, istasangiz albatta ya'ni ehtiyoj sessangiz!</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-6">
                    <h4>Birinchi telegram botim haqida!</h4>
                    <p>Bu bot asosan ob-havo haqida, siz istalgan payt o'z viloyatingiz ob-havosini bilib turishingiz
                        mumkin. 👉 <a rel="nofollow"
                                      href="https://t.me/eralionlineobhavobot"
                                      target="_parent">Ob-havo botim</a></p>
                </div>
                <div class="col-lg-6">
                    <h4>Ikkinchi telegram botim haqida!</h4>
                    <p>Bu bot Namoz vaqini eslatib turish uchun qurilgan. Uni vaqti qayerdan keladi desangiz,
                        <a rel="nofollow" href="https://islom.uz/" target="_parent">Islom.uz</a> saytidan API chiqarib
                        olganman. Bot bilan tanishing. 👉 <a rel="nofollow" href="https://t.me/erali_namoz_vaqti_bot"
                                                             target="_parent">Namoz vaqti botim</a></p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <h4>Va eng oxirgi Django Framework'da tayyorlangan MaxWay loyiham</h4>
                    <p>Bu meni oxirgi Django Frameworkda qilgan loyiham. MaxWay ya'ni onlayn Fas-Food magazin, unda
                        Dashboard qismlari va karzina qismi ham bor. Bemalol buyurtma berish mumkin 👉
                        <a rel="nofollow" href="https://eralidev.pythonanywhere.com/" target="_parent">MaxWay</a>,
                        Pastroqda men bilan bog'lanish uchun telegram manzil, Linkedin Github manzilim ko'rsatib o'tilgan.</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <ul class="social-icons">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-github"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>


        </div>
    </section>

{% endblock %}

templates/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
</head>

<body>
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <!-- Header -->
    <header class="">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="{% url 'blogapp:index' %}">
                    <h2>EraliDev Blog<em>.</em></h2>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blogapp:index' %}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blogapp:about' %}">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blogapp:blog' %}">Blog</a>
                        </li>
{#                        <li class="nav-item">#}
{#                            <a class="nav-link" href="#">Post Details</a>#}
{#                        </li>#}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blogapp:contact' %}">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blogapp:logout' %}">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    {% block content %} {% endblock %}

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="social-icons">
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Instagram</a></li>
                        <li><a href="https://t.me/eraliitcoder">Telegram</a></li>
                        <li><a href="#">Linkedin</a></li>
                        <li><a href="https://github.com/eraliabd">Github</a></li>
                    </ul>
                </div>
                <div class="col-lg-12">
                    <div class="copyright-text">
                        <p>&copy; Copyright 2022 EraliDev Blog | Programming: <a rel="nofollow" href="https://templatemo.com" target="_parent">Python</a></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>
    <script src="{% static 'assets/js/slick.js' %}"></script>
    <script src="{% static 'assets/js/isotope.js' %}"></script>
    <script src="{% static 'assets/js/accordions.js' %}"></script>

    <script language="text/Javascript">
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t) { //declaring the array outside of the
            if (!cleared[t.id]) { // function makes it static and global
                cleared[t.id] = 1; // you could use true and false, but that's more typing
                t.value = ''; // with more chance of typos
                t.style.color = '#fff';
            }
        }
    </script>
</body>

</html>

templates/blog.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Blog Posts{% endblock %}</title>
{% block content %}
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Recent Posts</h4>
                            <h2>OUR RECENT BLOG ENTRIES</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->

{#    <section class="call-to-action">#}
{#        <div class="container">#}
{#            <div class="row">#}
{#                <div class="col-lg-12">#}
{#                    <div class="main-content">#}
{#                        <div class="row">#}
{#                            <div class="col-lg-8">#}
{#                                <span>Stand Blog HTML5 Template</span>#}
{#                                <h4>Creative HTML Template For Bloggers!</h4>#}
{#                            </div>#}
{#                            <div class="col-lg-4">#}
{#                                <div class="main-button">#}
{#                                    <a href="" target="_parent">Download#}
{#                                        Now!</a>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}


    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            {% for post in posts %}
                                <div class="col-lg-6">
                                    <div class="blog-post">
                                        <div class="blog-thumb">
                                            <img src="/media/{{ post.image }}" alt="image">
                                        </div>
                                        <div class="down-content">
                                            <span>{{ post.title }}</span>
                                            <a href="{{ post.get_absolute_url }}"><h4>{{ post.small }}</h4></a>
                                            <ul class="post-info">
                                                <li><a href="#">{{ post.author }}</a></li>
                                                <li><a href="#">{{ post.publish }}</a></li>
                                                {% with comments.count as total_comments %}
                                                    <li><a href="#">{{ total_comments }} comment{{ total_comments|pluralize }}</a></li>
                                                {% endwith %}
                                            </ul>
                                            <p>{{ post.body|truncatewords:20 }}</p>
                                            <div class="post-options">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <ul class="post-tags">
                                                            <li><i class="fa fa-bolt"></i></li>
                                                            <li><a href="#">EraliDev</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="col-lg-12">
                                <div class="page-numbers" style="padding-left: 20px;">
                                    {% include "paginator.html" with page=page_obj %}
                                </div>
{#                                <div class="page-numbers">#}
{#                                    {% if page.has_previous %}#}
{#                                        <a style="font-size: 20px;" href="?page={{ page.previous_page_number }}">< previous&nbsp;&nbsp;&nbsp;</a>#}
{#                                    {% endif %}#}
{#                                    <a style="font-size: 20px;" href="#">page - {{ page.number }} of {{ page.paginator.num_pages }}</a>#}
{#                                    {% if page.has_next %}#}
{#                                        <a style="font-size: 20px;" href="?page={{ page.next_page_number }}">&nbsp;&nbsp;&nbsp;next ></a>#}
{#                                    {% endif %}#}
{#                                </div>#}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="sidebar">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="sidebar-item search">
                                    <form id="search_form" name="gs" method="GET" action="search">
                                        <input type="search" name="q" class="searchText" placeholder="Search post..."
                                               autocomplete="on">
                                    </form>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="sidebar-item recent-posts">
                                    <div class="sidebar-heading">
                                        <h2>Recent Posts</h2>
                                    </div>
                                    <div class="content">
                                        <ul>
                                            {% for post in posts %}
                                                <li><a href="{{ post.get_absolute_url }}">
                                                    <h5>{{ post.small }}</h5>
                                                    <span>{{ post.publish }}</span>
                                                </a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="sidebar-item categories">
                                    <div class="sidebar-heading">
                                        <h2>Categories</h2>
                                    </div>
                                    <div class="content">
                                        <ul>
                                            {% for post in posts %}
                                            <li><a href="{{ post.get_absolute_url }}">- {{ post.category }}</a></li>
                                            {% endfor %}
{#                                            <li><a href="#">- Awesome Layouts</a></li>#}
{#                                            <li><a href="#">- Creative Ideas</a></li>#}
{#                                            <li><a href="#">- Responsive Templates</a></li>#}
{#                                            <li><a href="#">- HTML5 / CSS3 Templates</a></li>#}
{#                                            <li><a href="#">- Creative &amp; Unique</a></li>#}
                                        </ul>
                                    </div>
                                </div>
                            </div>
{#                            <div class="col-lg-12">#}
{#                                <div class="sidebar-item tags">#}
{#                                    <div class="sidebar-heading">#}
{#                                        <h2>Tag Clouds</h2>#}
{#                                    </div>#}
{#                                    <div class="content">#}
{#                                        <ul>#}
{#                                            <li><a href="#">Lifestyle</a></li>#}
{#                                            <li><a href="#">Creative</a></li>#}
{#                                            <li><a href="#">HTML5</a></li>#}
{#                                            <li><a href="#">Inspiration</a></li>#}
{#                                            <li><a href="#">Motivation</a></li>#}
{#                                            <li><a href="#">PSD</a></li>#}
{#                                            <li><a href="#">Responsive</a></li>#}
{#                                        </ul>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
{% load static%}
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Login</title>

        <!-- Bootstrap CSS-->
        <link href="{% static 'vendor1/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">
        <!-- Main CSS-->
        <link href="{% static 'css/theme.css' %}" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper">
        <div class="page-content--bge5">
            <div class="container">
                <div class="login-wrap">
                    <div class="login-content">
                        <div class="login-logo">
                            <a href="#">
                                <img src="{% static 'images/icon/logo.png' %}" alt="CoolAdmin">
                            </a>
                        </div>
                        <div class="login-form">

                            <form  method="post">
                                {% csrf_token%}
                                <div class="form-group">
                                    <label>username </label>
                                    <input class="au-input au-input--full" type="username" name="username" placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <label>Password</label>
                                    <input class="au-input au-input--full" type="password" name="password" placeholder="Password">
                                </div>

                                <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">sign in</button>
                            </form>
                            <a class="au-btn au-btn--block au-btn--blue m-b-20 text-center" href="{% url 'blogapp:signup' %}">signup</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

        <!-- Jquery JS-->
        <script src="{% static 'vendor1/jquery-3.2.1.min.js' %}"></script>
        <!-- Bootstrap JS-->
        <script src="{% static 'vendor1/bootstrap-4.1/popper.min.js' %}"></script>
        <script src="{% static 'vendor1/bootstrap-4.1/bootstrap.min.js' %}"></script>
        <!-- Vendor JS       -->

        <!-- Main JS-->
        <script src="{% static 'js/main.js' %}"></script>
</body>

</html>
<!-- end document-->

templates/paginator.html
{% load static %}
{#{% if page.has_previous %}#}
{#    <a style="font-size: 20px;" href="?page={{ page.previous_page_number }}"><< previous&nbsp;&nbsp;&nbsp;</a>#}
{#{% endif %}#}
{#    <a style="font-size: 20px;" href="#">page - {{ page.number }} of {{ page.paginator.num_pages }}</a>#}
{#{% if page.has_next %}#}
{#    <a style="font-size: 20px;" href="?page={{ page.next_page_number }}">&nbsp;&nbsp;&nbsp;next >></a>#}
{#{% endif %}#}



{% load static %}
<ul class="pagination justify-content-end mb-0">
{% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <<{#            <i class="fas fa-angle-left"></i>#}
            <span class="sr-only">Previous</span>
        </a>
    </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">
            <<{#            <i class="fas fa-angle-left"></i>#}
            <span class="sr-only">Previous</span>
        </a>
    </li>
{% endif %}

{% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active">
        <a class="page-link" href="?page={{ i }}">{{ page_obj.number }}</a>
      </li>
    {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
    <li class="page-item">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endif %}
{% endfor %}

{% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
    <li><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
{% endif %}

{% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>{#          <i class="fas fa-angle-right"></i>#}
          <span class="sr-only">Next</span>
        </a>
      </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">
            >>{#            <i class="fas fa-angle-right"></i>#}
            <span class="sr-only">Next</span>
        </a>
    </li>
{% endif %}
</ul>